### ISSUE TITLE
Error trying to launch the code

### ISSUE THREAD

**Issue by rbrivio** [fdraxler/PyTorch-AutoNEB#6]
Hello,

very interesting paper! I would like to reproduce the results and play a bit around with the code, but I encounter some issues. I am running the code in a conda environment where I installed the recommended versions for the code (Python 3.6.5, torch 0.4.0) and I tried different possible config files, but I found an error. Maybe it is something you have encountered and you know how to fix it.

Here is my error trace after giving `python main.py proj configs/cifar10-resnet20.yaml`

Traceback (most recent call last):
  File "main.py", line 131, in <module>
    main()
  File "main.py", line 70, in main
    model, minima_count, min_config, lex_config = read_config_file(project_config_path)
  File "main.py", line 35, in read_config_file
    model = ModelWrapper(model)
  File "C:\Users\Riccardo\Desktop\PyTorch-AutoNEB\torch_autoneb\models\__init__.py", line 82, in \_\_init\_\_
    buffers = model.buffers()
  File "C:\Users\Riccardo\anaconda3\envs\neb\lib\site-packages\torch\nn\modules\module.py", line 532, in \_\_getattr\_\_
    type(self).\_\_name\_\_, name))
AttributeError: 'DataModel' object has no attribute 'buffers'

Thank you in advance.

Riccardo

**Comment by fdraxler** [comment]
Dear Riccardo,

thanks for your interest in this project! I updated the code to run with Python 3.10 and PyTorch 1.12.1. I ran a quick test and it seems like the above error does not occur. If you encounter further issues, please do not hesitate to re-open the issue or opening another one.

Best regards,
Felix
